/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BondedFacilitatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLAIM_TIMEOUT"
      | "bondBalance"
      | "claimPayment"
      | "commitPayment"
      | "depositBond"
      | "getAvailableBond"
      | "getExposure"
      | "paymentFacilitator"
      | "payments"
      | "releasePayment"
      | "token"
      | "totalCommitted"
      | "withdrawBond"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondDeposited"
      | "BondWithdrawn"
      | "PaymentClaimed"
      | "PaymentCommitted"
      | "PaymentReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLAIM_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bondBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitPayment",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableBond",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExposure",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentFacilitator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalCommitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBond",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLAIM_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bondBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBond",
    data: BytesLike
  ): Result;
}

export namespace BondDepositedEvent {
  export type InputTuple = [facilitator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [facilitator: string, amount: bigint];
  export interface OutputObject {
    facilitator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondWithdrawnEvent {
  export type InputTuple = [facilitator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [facilitator: string, amount: bigint];
  export interface OutputObject {
    facilitator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentClaimedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    provider: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    provider: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCommittedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    provider: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    provider: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [paymentId: BytesLike];
  export type OutputTuple = [paymentId: string];
  export interface OutputObject {
    paymentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BondedFacilitator extends BaseContract {
  connect(runner?: ContractRunner | null): BondedFacilitator;
  waitForDeployment(): Promise<this>;

  interface: BondedFacilitatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLAIM_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  bondBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  claimPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [void],
    "nonpayable"
  >;

  commitPayment: TypedContractMethod<
    [paymentId: BytesLike, provider: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositBond: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvailableBond: TypedContractMethod<
    [facilitator: AddressLike],
    [bigint],
    "view"
  >;

  getExposure: TypedContractMethod<
    [facilitator: AddressLike],
    [bigint],
    "view"
  >;

  paymentFacilitator: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean] & {
        provider: string;
        amount: bigint;
        committedAt: bigint;
        deadline: bigint;
        settled: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  releasePayment: TypedContractMethod<
    [paymentId: BytesLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  totalCommitted: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawBond: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLAIM_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bondBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimPayment"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike, provider: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositBond"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAvailableBond"
  ): TypedContractMethod<[facilitator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExposure"
  ): TypedContractMethod<[facilitator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "paymentFacilitator"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean] & {
        provider: string;
        amount: bigint;
        committedAt: bigint;
        deadline: bigint;
        settled: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalCommitted"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawBond"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BondDeposited"
  ): TypedContractEvent<
    BondDepositedEvent.InputTuple,
    BondDepositedEvent.OutputTuple,
    BondDepositedEvent.OutputObject
  >;
  getEvent(
    key: "BondWithdrawn"
  ): TypedContractEvent<
    BondWithdrawnEvent.InputTuple,
    BondWithdrawnEvent.OutputTuple,
    BondWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PaymentClaimed"
  ): TypedContractEvent<
    PaymentClaimedEvent.InputTuple,
    PaymentClaimedEvent.OutputTuple,
    PaymentClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCommitted"
  ): TypedContractEvent<
    PaymentCommittedEvent.InputTuple,
    PaymentCommittedEvent.OutputTuple,
    PaymentCommittedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;

  filters: {
    "BondDeposited(address,uint256)": TypedContractEvent<
      BondDepositedEvent.InputTuple,
      BondDepositedEvent.OutputTuple,
      BondDepositedEvent.OutputObject
    >;
    BondDeposited: TypedContractEvent<
      BondDepositedEvent.InputTuple,
      BondDepositedEvent.OutputTuple,
      BondDepositedEvent.OutputObject
    >;

    "BondWithdrawn(address,uint256)": TypedContractEvent<
      BondWithdrawnEvent.InputTuple,
      BondWithdrawnEvent.OutputTuple,
      BondWithdrawnEvent.OutputObject
    >;
    BondWithdrawn: TypedContractEvent<
      BondWithdrawnEvent.InputTuple,
      BondWithdrawnEvent.OutputTuple,
      BondWithdrawnEvent.OutputObject
    >;

    "PaymentClaimed(bytes32,address,uint256)": TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;
    PaymentClaimed: TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;

    "PaymentCommitted(bytes32,address,uint256)": TypedContractEvent<
      PaymentCommittedEvent.InputTuple,
      PaymentCommittedEvent.OutputTuple,
      PaymentCommittedEvent.OutputObject
    >;
    PaymentCommitted: TypedContractEvent<
      PaymentCommittedEvent.InputTuple,
      PaymentCommittedEvent.OutputTuple,
      PaymentCommittedEvent.OutputObject
    >;

    "PaymentReleased(bytes32)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
  };
}
