/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDeferredPaymentEscrow {
  export type VoucherStruct = {
    id: BytesLike;
    buyer: AddressLike;
    seller: AddressLike;
    valueAggregate: BigNumberish;
    asset: AddressLike;
    timestamp: BigNumberish;
    nonce: BigNumberish;
    escrow: AddressLike;
    chainId: BigNumberish;
  };

  export type VoucherStructOutput = [
    id: string,
    buyer: string,
    seller: string,
    valueAggregate: bigint,
    asset: string,
    timestamp: bigint,
    nonce: bigint,
    escrow: string,
    chainId: bigint
  ] & {
    id: string;
    buyer: string;
    seller: string;
    valueAggregate: bigint;
    asset: string;
    timestamp: bigint;
    nonce: bigint;
    escrow: string;
    chainId: bigint;
  };

  export type EscrowAccountStruct = {
    balance: BigNumberish;
    thawingAmount: BigNumberish;
    thawEndTime: BigNumberish;
  };

  export type EscrowAccountStructOutput = [
    balance: bigint,
    thawingAmount: bigint,
    thawEndTime: bigint
  ] & { balance: bigint; thawingAmount: bigint; thawEndTime: bigint };
}

export interface IDeferredPaymentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "collect"
      | "collectMany"
      | "deposit"
      | "getAccount"
      | "thaw"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Collected"
      | "Deposited"
      | "ThawStarted"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "collect",
    values: [IDeferredPaymentEscrow.VoucherStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectMany",
    values: [IDeferredPaymentEscrow.VoucherStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "thaw", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "collect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectMany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAccount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "thaw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CollectedEvent {
  export type InputTuple = [
    voucherId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    voucherId: string,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    voucherId: string;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThawStartedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    thawEndTime: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    amount: bigint,
    thawEndTime: bigint
  ];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    thawEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDeferredPaymentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IDeferredPaymentEscrow;
  waitForDeployment(): Promise<this>;

  interface: IDeferredPaymentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  collect: TypedContractMethod<
    [voucher: IDeferredPaymentEscrow.VoucherStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  collectMany: TypedContractMethod<
    [vouchers: IDeferredPaymentEscrow.VoucherStruct[], signatures: BytesLike[]],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getAccount: TypedContractMethod<
    [buyer: AddressLike],
    [IDeferredPaymentEscrow.EscrowAccountStructOutput],
    "view"
  >;

  thaw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "collect"
  ): TypedContractMethod<
    [voucher: IDeferredPaymentEscrow.VoucherStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectMany"
  ): TypedContractMethod<
    [vouchers: IDeferredPaymentEscrow.VoucherStruct[], signatures: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccount"
  ): TypedContractMethod<
    [buyer: AddressLike],
    [IDeferredPaymentEscrow.EscrowAccountStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "thaw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Collected"
  ): TypedContractEvent<
    CollectedEvent.InputTuple,
    CollectedEvent.OutputTuple,
    CollectedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "ThawStarted"
  ): TypedContractEvent<
    ThawStartedEvent.InputTuple,
    ThawStartedEvent.OutputTuple,
    ThawStartedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Collected(bytes32,address,address,uint256)": TypedContractEvent<
      CollectedEvent.InputTuple,
      CollectedEvent.OutputTuple,
      CollectedEvent.OutputObject
    >;
    Collected: TypedContractEvent<
      CollectedEvent.InputTuple,
      CollectedEvent.OutputTuple,
      CollectedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "ThawStarted(address,uint256,uint64)": TypedContractEvent<
      ThawStartedEvent.InputTuple,
      ThawStartedEvent.OutputTuple,
      ThawStartedEvent.OutputObject
    >;
    ThawStarted: TypedContractEvent<
      ThawStartedEvent.InputTuple,
      ThawStartedEvent.OutputTuple,
      ThawStartedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
